### ISSUE TITLE
Post Script command for setting value to environment

### ISSUE THREAD

**Issue by shrijan00003** [shrijan00003/restler#20]
## Description
The post script command should be defined along with requests. The post scripts command should be defined as 

```
....
After:
  Env:
    AUTH0_TOKEN: Body[access_token]
    CONTENT_TYPE: Header[Content Type]
```

Here, Body and Headers will be the reserved word for the response header and Body of the of the response.
